# Generated by Django 4.1 on 2023-05-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.CharField(max_length=15, unique=True, verbose_name='Student ID')),
                ('std_fname', models.CharField(max_length=50, verbose_name='First Name')),
                ('std_lname', models.CharField(default=None, max_length=50, verbose_name='Last Name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10, verbose_name='Gender')),
                ('max_total_marks', models.CharField(max_length=4, verbose_name='Maximum Total Marks')),
                ('total_marks', models.CharField(max_length=4, verbose_name='Gained Total Marks')),
                ('percentage', models.CharField(max_length=3, verbose_name='Percentage')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
